export { default as AlbumService } from "./albums";
export { default as LoginService } from "./login";
export { default as TokenService } from "./token";
export { default as UserService } from "./user";
export { default as ReviewService } from "./reviews";
export { default as UserAlbumService } from "./user_album";
export { default as ArtistService } from "./artists";
export { default as GenreService } from "./genres";
export { default as SubgenreService } from "./subgenres";
