version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: greatest_albums
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  flyway:
    image: flyway/flyway
    command: -url='jdbc:mysql://db/greatest_albums?verifyServerCertificate=false&allowPublicKeyRetrieval=true' -user=user
      -password=password -connectRetries=5 migrate
    volumes:
      - ./database/base:/flyway/sql
    depends_on:
      - db
volumes:
  db: 