version: "3"
services:
  api:
    build: ./server
    ports:
      - 8080:8080
    environment:
      HOST: "db"
      USERNAME: "kjones15"
      PASSWORD: "lw0thbd0jJctDKC9"
      DB: "kjones15"
    depends_on:
      - flyway
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: kjones15
      MYSQL_USER: kjones15
      MYSQL_PASSWORD: lw0thbd0jJctDKC9
      MYSQL_ROOT_PASSWORD: lw0thbd0jJctDKC9
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  flyway:
    image: flyway/flyway
    command: -url='jdbc:mysql://db/kjones15?verifyServerCertificate=false&allowPublicKeyRetrieval=true' -user=kjones15
      -password=lw0thbd0jJctDKC9 -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
volumes:
  db: 